[package]
name = "request-spammer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.20.1"
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
